import "@radix-ui/themes/styles.css";
import "./theme.config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./navbar";
import { Theme } from "@radix-ui/themes";
import { ReactQueryClientProvider } from "./utils/reactQueryProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme>
          <ReactQueryClientProvider>
            <NavBar />
            <main className="px-6 py-4">{children}</main>
          </ReactQueryClientProvider>
        </Theme>
      </body>
    </html>
  );
}
